from base_model_and_evolver import Model, Evolver
from env_models_and_evolvers import *

env_details = {
    'Acrobot-v1': dict(
        env_config_params=dict(OBS_DIM=6,
                               ACTION_DIM=3,
                               G=100,
                               N=10,
                               K=5,
                               NUM_EPS_PER_EVAL=3,
                               ENV_NAME='Acrobot-v1'),
        env_model=Model,
        env_evolver=Evolver),
    "CartPole-v1": dict(
        env_config_params=dict(OBS_DIM=4,
                               ACTION_DIM=2,
                               G=20,
                               N=10,
                               K=5,
                               NUM_EPS_PER_EVAL=3,
                               ENV_NAME='CartPole-v1'),
        env_model=Model,
        env_evolver=Evolver),
    "LunarLander-v2": dict(
        env_config_params=dict(OBS_DIM=8,
                               ACTION_DIM=4,
                               G=300,
                               N=20,
                               K=10,
                               NUM_EPS_PER_EVAL=5,
                               ENV_NAME="LunarLander-v2"),
        env_model=Model,
        env_evolver=Evolver),
    "MountainCar-v0": dict(
        env_config_params=dict(OBS_DIM=2,
                               ACTION_DIM=3,
                               G=100,
                               N=20,
                               K=10,
                               NUM_EPS_PER_EVAL=5,
                               ENV_NAME="MountainCar-v0"),
        env_model=Model,
        env_evolver=Evolver),
    "Pendulum-v1": dict(
        env_config_params=dict(OBS_DIM=3,
                               ACTION_DIM=5,
                               G=100,
                               N=20,
                               K=10,
                               NUM_EPS_PER_EVAL=5,
                               ENV_NAME="Pendulum-v1"),
        env_model=PendulumV1Model,
        env_evolver=Evolver),
    'BipedalWalker-v3': dict(
        env_config_params=dict(OBS_DIM=24,
                               ACTION_DIM=4,
                               G=200,
                               N=10,
                               K=5,
                               NUM_EPS_PER_EVAL=3,
                               ENV_NAME='BipedalWalker-v3'),
        env_model=BipedalWalkerModel,
        env_evolver=Evolver),
    'FrozenLake-v1-8x8': dict(
        env_config_params=dict(OBS_DIM=8,
                               ACTION_DIM=8,
                               G=300,
                               N=10,
                               K=5,
                               NUM_EPS_PER_EVAL=1,
                               ENV_NAME='FrozenLake-v1'),
        env_model=Model,
        env_evolver=FrozenLakeEvolver),
    'FrozenLake-v1-4x4': dict(
        env_config_params=dict(OBS_DIM=4,
                               ACTION_DIM=4,
                               G=300,
                               N=20,
                               K=5,
                               NUM_EPS_PER_EVAL=1,
                               ENV_NAME='FrozenLake-v1'),
        env_model=Model,
        env_evolver=FrozenLakeEvolver),
    'Cliffwalking-v0': dict(
        env_config_params=dict(OBS_DIM=4,
                               ACTION_DIM=12,
                               G=100,
                               N=20,
                               K=5,
                               NUM_EPS_PER_EVAL=1,
                               ENV_NAME='Cliffwalking-v0'),
        env_model=Model,
        env_evolver=FrozenLakeEvolver)
}
